version: '3.8'

services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ./apps/backend:/app
      - ./data:/data
    environment:
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./aitax.db}
      - SECRET_KEY=${SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMA_HOST=${CHROMA_HOST:-chroma}
      - CHROMA_PORT=${CHROMA_PORT:-8000}
      - CHROMA_COLLECTION_PREFIX=${CHROMA_COLLECTION_PREFIX:-dev}
      - DEBUG=${DEBUG:-true}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    depends_on:
      - chroma
    networks:
      - aitax-network

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:${BACKEND_PORT:-8000}
    depends_on:
      - backend
    networks:
      - aitax-network

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - chroma-data:/chroma/chroma
    ports:
      - "8100:8000"
    networks:
      - aitax-network

networks:
  aitax-network:
    driver: bridge

volumes:
  chroma-data:
